@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Arc
class CheminATrouver
class Dijkstra
class DijkstraTest
class DijkstraTools
class GraphDirectoryImporter
class GraphImporter
class Graphe
class GrapheHHAdj
class GrapheLAdj
class GrapheLArcs
class GrapheMAdj
interface IGraphe << interface >>
interface IGrapheConst << interface >>
class IGrapheTest
class Main

CheminATrouver         "1" *-[#595959,plain]-> "sd_arc\n1" Arc                    
CheminATrouver         "1" *-[#595959,plain]-> "g\n1" IGraphe                
DijkstraTest            -[#595959,dashed]->  GraphDirectoryImporter : "«create»"
DijkstraTest            -[#595959,dashed]->  GrapheHHAdj            : "«create»"
GraphDirectoryImporter "1" *-[#595959,plain]-> "g\n1" IGraphe                
GraphImporter           -[#595959,dashed]->  Arc                    : "«create»"
Graphe                  -[#008200,dashed]-^  IGraphe                
GrapheHHAdj             -[#008200,dashed]-^  IGraphe                
GrapheLAdj              -[#595959,dashed]->  Arc                    : "«create»"
GrapheLAdj              -[#008200,dashed]-^  IGraphe                
GrapheLArcs             -[#595959,dashed]->  Arc                    : "«create»"
GrapheLArcs            "1" *-[#595959,plain]-> "arcs\n*" Arc                    
GrapheLArcs             -[#008200,dashed]-^  IGraphe                
GrapheMAdj              -[#008200,dashed]-^  IGraphe                
IGraphe                 -[#008200,plain]-^  IGrapheConst           
IGrapheTest             -[#595959,dashed]->  GrapheHHAdj            : "«create»"
IGrapheTest             -[#595959,dashed]->  GrapheLAdj             : "«create»"
IGrapheTest             -[#595959,dashed]->  GrapheLArcs            : "«create»"
IGrapheTest             -[#595959,dashed]->  GrapheMAdj             : "«create»"
IGrapheTest            "1" *-[#595959,plain]-> "graphes\n*" IGraphe                
Main                    -[#595959,dashed]->  GraphDirectoryImporter : "«create»"
Main                    -[#595959,dashed]->  GrapheHHAdj            : "«create»"
Main                    -[#595959,dashed]->  GrapheLAdj             : "«create»"
Main                    -[#595959,dashed]->  GrapheLArcs            : "«create»"
Main                    -[#595959,dashed]->  GrapheMAdj             : "«create»"
Main                   "1" *-[#595959,plain]-> "prototypes\n*" IGraphe                
@enduml
